package com.bank.credit_bank.infrastructure.presenter.soap.controller;

import com.bank.credit_bank.infrastructure.aop.annotation.TransactionalUseCase;
import com.bank.credit_bank.infrastructure.presenter.soap.schema.request.*;
import com.bank.credit_bank.infrastructure.presenter.soap.schema.response.*;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://bank.com/credit_card", name = "CreditCardPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreditCardControllerSOAP {

    @WebMethod(action = "http://bank.com/credit_card/retrieveBalance")
    @WebResult(name = "retrieveBalanceResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    RetrieveBalanceResponse retrieveBalance(

            @WebParam(partName = "parameters", name = "retrieveBalanceRequest", targetNamespace = "http://bank.com/credit_card")
            RetrieveBalanceRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/initiatePayment")
    @WebResult(name = "initiatePaymentResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    InitiatePaymentResponse initiatePayment(

            @WebParam(partName = "parameters", name = "initiatePaymentRequest", targetNamespace = "http://bank.com/credit_card")
            InitiatePaymentRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/initiateConsumption")
    @WebResult(name = "initiateConsumptionResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    InitiateConsumptionResponse initiateConsumption(

            @WebParam(partName = "parameters", name = "initiateConsumptionRequest", targetNamespace = "http://bank.com/credit_card")
            InitiateConsumptionRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/exchangeConsumption")
    @WebResult(name = "exchangeConsumptionResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    ExchangeConsumptionResponse exchangeConsumption(

            @WebParam(partName = "parameters", name = "exchangeConsumptionRequest", targetNamespace = "http://bank.com/credit_card")
            ExchangeConsumptionRequest parameters
    );

    @WebMethod(action = "http://bank.com/credit_card/retrieveConsumption")
    @WebResult(name = "retrieveConsumptionResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    RetrieveConsumptionResponse retrieveConsumption(

            @WebParam(partName = "parameters", name = "retrieveConsumptionRequest", targetNamespace = "http://bank.com/credit_card")
            RetrieveConsumptionRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/controlConsumption")
    @WebResult(name = "controlConsumptionResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    ControlConsumptionResponse controlConsumption(

            @WebParam(partName = "parameters", name = "controlConsumptionRequest", targetNamespace = "http://bank.com/credit_card")
            ControlConsumptionRequest parameters
    );

    @WebMethod(action = "http://bank.com/credit_card/retrievePayment")
    @WebResult(name = "retrievePaymentResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    RetrievePaymentResponse retrievePayment(

            @WebParam(partName = "parameters", name = "retrievePaymentRequest", targetNamespace = "http://bank.com/credit_card")
            RetrievePaymentRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/initiateCard")
    @WebResult(name = "initiateCardResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    InitiateCardResponse initiateCard(

            @WebParam(partName = "parameters", name = "initiateCardRequest", targetNamespace = "http://bank.com/credit_card")
            InitiateCardRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/controlCard")
    @WebResult(name = "controlCardResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    ControlCardResponse controlCard(

            @WebParam(partName = "parameters", name = "controlCardRequest", targetNamespace = "http://bank.com/credit_card")
            ControlCardRequest parameters
    );

    @TransactionalUseCase
    @WebMethod(action = "http://bank.com/credit_card/controlPayment")
    @WebResult(name = "controlPaymentResponse", targetNamespace = "http://bank.com/credit_card", partName = "parameters")
    ControlPaymentResponse controlPayment(

            @WebParam(partName = "parameters", name = "controlPaymentRequest", targetNamespace = "http://bank.com/credit_card")
            ControlPaymentRequest parameters
    );
}
